const productos = [
	{
		id: 1,
		nombre: 'Hamburguesa Clásica',
		imagen: 'img/hamburguesa.jpg',
		descripcion: 'Deliciosa hamburguesa con ingredientes frescos.',
		precio: 10,
		stock: 20,
	},
	{
		id: 2,
		nombre: 'Patatas Fritas',
		imagen: 'img/patatas.jpg',
		descripcion: 'Crujientes patatas fritas con sal.',
		precio: 5,
		stock: 50,
	},
	{
		id: 3,
		nombre: 'Pizza Margarita',
		imagen: 'img/pizza.jpg',
		descripcion: 'Pizza con salsa de tomate, mozzarella y albahaca.',
		precio: 12,
		stock: 15,
	},
	{
		id: 4,
		nombre: 'Ensalada César',
		imagen: 'img/ensalada.jpg',
		descripcion:
			'Ensalada con pollo, lechuga, queso parmesano y aderezo César.',
		precio: 8,
		stock: 30,
	},
	{
		id: 5,
		nombre: 'Tacos de Pollo',
		imagen: 'img/tacos.jpg',
		descripcion: 'Tacos rellenos de pollo, lechuga y salsa.',
		precio: 7,
		stock: 25,
	},
	{
		id: 6,
		nombre: 'Sándwich de Jamón',
		imagen: 'img/sandwich.jpg',
		descripcion: 'Sándwich con jamón, queso, lechuga y tomate.',
		precio: 6,
		stock: 40,
	},
	{
		id: 7,
		nombre: 'Sopa de Tomate',
		imagen: 'img/sopa.jpg',
		descripcion: 'Sopa caliente de tomate con albahaca.',
		precio: 4,
		stock: 35,
	},
	{
		id: 8,
		nombre: 'Pollo Asado',
		imagen: 'img/pollo.jpg',
		descripcion: 'Pollo asado con hierbas y especias.',
		precio: 15,
		stock: 10,
	},
	{
		id: 9,
		nombre: 'Pasta Alfredo',
		imagen: 'img/pasta.jpg',
		descripcion: 'Pasta con salsa Alfredo y queso parmesano.',
		precio: 11,
		stock: 20,
	},
	{
		id: 10,
		nombre: 'Helado de Vainilla',
		imagen: 'img/helado.jpg',
		descripcion: 'Helado cremoso de vainilla.',
		precio: 3,
		stock: 50,
	},
	{
		id: 11,
		nombre: 'Hamburguesa Clásica',
		imagen: 'img/hamburguesa.jpg',
		descripcion: 'Deliciosa hamburguesa con ingredientes frescos.',
		precio: 10,
		stock: 20,
	},
	{
		id: 12,
		nombre: 'Patatas Fritas',
		imagen: 'img/patatas.jpg',
		descripcion: 'Crujientes patatas fritas con sal.',
		precio: 5,
		stock: 50,
	},
	{
		id: 13,
		nombre: 'Pizza Margarita',
		imagen: 'img/pizza.jpg',
		descripcion: 'Pizza con salsa de tomate, mozzarella y albahaca.',
		precio: 12,
		stock: 15,
	},
	{
		id: 14,
		nombre: 'Ensalada César',
		imagen: 'img/ensalada.jpg',
		descripcion:
			'Ensalada con pollo, lechuga, queso parmesano y aderezo César.',
		precio: 8,
		stock: 30,
	},
	{
		id: 15,
		nombre: 'Tacos de Pollo',
		imagen: 'img/tacos.jpg',
		descripcion: 'Tacos rellenos de pollo, lechuga y salsa.',
		precio: 7,
		stock: 25,
	},
	{
		id: 16,
		nombre: 'Sándwich de Jamón',
		imagen: 'img/sandwich.jpg',
		descripcion: 'Sándwich con jamón, queso, lechuga y tomate.',
		precio: 6,
		stock: 40,
	},
	{
		id: 17,
		nombre: 'Sopa de Tomate',
		imagen: 'img/sopa.jpg',
		descripcion: 'Sopa caliente de tomate con albahaca.',
		precio: 4,
		stock: 35,
	},
	{
		id: 18,
		nombre: 'Pollo Asado',
		imagen: 'img/pollo.jpg',
		descripcion: 'Pollo asado con hierbas y especias.',
		precio: 15,
		stock: 10,
	},
	{
		id: 19,
		nombre: 'Pasta Alfredo',
		imagen: 'img/pasta.jpg',
		descripcion: 'Pasta con salsa Alfredo y queso parmesano.',
		precio: 11,
		stock: 20,
	},
	{
		id: 20,
		nombre: 'Helado de Vainilla',
		imagen: 'img/helado.jpg',
		descripcion: 'Helado cremoso de vainilla.',
		precio: 3,
		stock: 50,
	},
]
